# Generated by Django 2.1.4 on 2018-12-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_model_out',
        ),
    ]
