# Generated by Django 2.1.4 on 2018-12-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_news_model_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model_total',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
