# Generated by Django 2.1.4 on 2018-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181228_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model_total',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
