# Generated by Django 2.1.4 on 2018-12-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181228_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model_total',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
