# Generated by Django 2.1.4 on 2019-01-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181228_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_model_total',
            name='category',
            field=models.CharField(choices=[('N', 'Nowosc'), ('P', 'Polityka'), ('S', 'Sport')], default='N', max_length=1),
        ),
    ]
