# Generated by Django 2.1.4 on 2019-01-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_news_model_total_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlef', models.CharField(max_length=50)),
                ('textf', models.TextField(blank=True, null=True)),
                ('pricef', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
