# Generated by Django 2.1.4 on 2019-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190116_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model_total',
            name='category',
            field=models.CharField(choices=[('N', 'Nowosc'), ('P', 'Polityka'), ('S', 'Sport'), ('B', 'Biznes'), ('I', 'Inne')], default='N', max_length=1),
        ),
    ]
