# Generated by Django 2.1.4 on 2019-01-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190121_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='tekst',
        ),
    ]
